force-app/main/default/objects/Contract/fields/CB_Subscription__c.field-meta.xml
<CustomField>
    <fullName>CB_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CB Subscription</label>
    <referenceTo>chargebeeapps__CB_Subscription__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Unique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_Test_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_Test_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Test Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Is_VIP_Contract__c.field-meta.xml
<CustomField>
    <fullName>Is_VIP_Contract__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Clientes VIP, no tienen COBROS.</description>
    <label>Is VIP Contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_AC_start_date__c.field-meta.xml
<CustomField>
    <fullName>SM_AC_start_date__c</fullName>
    <label>AC start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Billing_status__c.field-meta.xml
<CustomField>
    <fullName>SM_Billing_status__c</fullName>
    <formula>IF(SM_Full_Payment__c =TRUE, &quot;PAYMENT COMPLETED&quot;,
	IF (SM_Charged_SB_Fees2__c = 0 ,&quot;WITHOUT PAYMENT REGISTER&quot;,
	   IF(
		  AND(
			 OR(ISPICKVAL(Status, &quot;Activated&quot;),ISPICKVAL(Status, &quot;Finalized&quot;)),
			 TEXT( SM_Way_of_Contract_Payment__c ) = &quot;Fix Term&quot;,
			 SM_Charged_SB_Fees2__c &gt;= SM_Plan_Months__c
		  ),
		  &quot;PAYMENT COMPLETED&quot;,
		  IF(
			 TODAY() &lt; SM_Next_installment_date__c  ,
			 &quot;PAYMENTS UP TO DATE&quot;,
			 IF(
				SM_Next_installment_date__c = TODAY() ,
				&quot;DUE TODAY&quot;,
				IF(TODAY() &gt; SM_Next_installment_date__c,
				   &quot;LATE PAYMENTS&quot;,
				   IF(
					  AND(
						 OR(ISPICKVAL(Status, &quot;Activated&quot;),ISPICKVAL(Status, &quot;Finalized&quot;)),
						 SM_Charged_SB_Fees2__c = 0,
						 SM_Plan_Months__c &gt; 0
					  ),
					  &quot;WITHOUT PAYMENT REGISTER&quot;,
					  &quot;&quot;
				   )
				)
			 )
		  )
	   )
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Email_to_send_contract__c.field-meta.xml
<CustomField>
    <fullName>SM_Email_to_send_contract__c</fullName>
    <label>Email to send contract</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Net_AC__c.field-meta.xml
<CustomField>
    <fullName>SM_Net_AC__c</fullName>
    <formula>SM_Total_ac__c + SM_IVU_State_AC__c + SM_IVU_Municipal_AC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Value AC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Net_Monthly_offer__c.field-meta.xml
<CustomField>
    <fullName>SM_Net_Monthly_offer__c</fullName>
    <formula>SM_Monthly_offer__c + SM_IVU_State_Monthly_offer__c + SM_IVU_Municipal_Monthly_offer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Monthly offer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Payment_Condition__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Condition__c</fullName>
    <label>Payment Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>SM_Payment_Method__c.SM_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>SM_Payment_Method__c.SM_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SM_Payment_Method__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Payment_methods__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_methods__c</fullName>
    <label>Payment methods Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Requires_AC_Payment__c.field-meta.xml
<CustomField>
    <fullName>SM_Requires_AC_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks that based on the product the Ac must be collected</description>
    <inlineHelpText>Marks that based on the product the Ac must be collected</inlineHelpText>
    <label>Requires AC Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Start_date__c.field-meta.xml
<CustomField>
    <fullName>SM_Start_date__c</fullName>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/SM_ACH_Order__c.object-meta.xml
<CustomObject>
    <label>ACH Order</label>
    <nameField>
        <displayFormat>ACH-{0000}</displayFormat>
        <label>ACH Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Apply_penalty__c.field-meta.xml
<CustomField>
    <fullName>SM_Apply_penalty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply penalty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>SM_Billing_Email__c</fullName>
    <label>Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Contract__c.field-meta.xml
<CustomField>
    <fullName>SM_Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>ACH Orders</relationshipLabel>
    <relationshipName>ACH_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Fee_to_collect__c.field-meta.xml
<CustomField>
    <fullName>SM_Fee_to_collect__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fee to collect</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Next_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Next_Transaction_Date__c</fullName>
    <label>Next Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Condition__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Condition__c</fullName>
    <label>Payment Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed value</fullName>
            </value>
            <value>
                <fullName>Dynamic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Count__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Count__c</fullName>
    <label>Payment Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Once</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Biweekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bimonthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semiannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>SM_Payment_Method__c</referenceTo>
    <relationshipLabel>ACH Orders</relationshipLabel>
    <relationshipName>ACH_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
            <value>
                <fullName>X CANCELED</fullName>
                <isActive>false</isActive>
                <label>X CANCELED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Late payment fee</fullName>
            </value>
            <value>
                <fullName>Suscripción</fullName>
                <isActive>false</isActive>
                <label>Suscripción</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Penalty_value__c.field-meta.xml
<CustomField>
    <fullName>SM_Penalty_value__c</fullName>
    <label>Penalty value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Total__c.field-meta.xml
<CustomField>
    <fullName>SM_Total__c</fullName>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Payment_Method__c/SM_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_Payment_Method__c/fields/SM_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking Account</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

scripts/apex/1-Nuevos Contratos - Crear ACH Orders.cls
// ┌───────────────────────────────────────────────────────────────┐
// │ Backfill masivo: Crear ACH Orders (AC / Subscription)          │
// │ Julio 2026 :: Carlos Alberto Lopez Prada                       │
// └───────────────────────────────────────────────────────────────┘

// ---------------- CONFIG ----------------
Boolean modoDryRun = false;   // true = simula, false = ejecuta
// ----------------------------------------

// 1️⃣ Query única — contratos ACH sin ACH Order
List<Contract> contratos = [
    SELECT Id, ContractNumber, SM_Payment_methods__c, Status,
           CB_Subscription__c, Is_Test_Contract__c, Is_VIP_Contract__c,
           SM_Email_to_send_contract__c, SM_Payment_Method__c,
           SM_Payment_Method__r.RecordType.Name,
           SM_AC_start_date__c, SM_Net_AC__c,
           SM_Start_date__c, SM_Net_Monthly_offer__c,
           SM_Requires_AC_Payment__c, Contract_Type__c, SM_Billing_status__c,
           RecordType.Name
    FROM Contract
    WHERE SM_Payment_methods__c = 'ACH'
      AND Status IN ('Payment Process', 'Activated')
      AND Is_Test_Contract__c = FALSE
      AND Is_VIP_Contract__c = FALSE
      AND CB_Subscription__c = null
      AND Contract_Type__c <> 'Dependent'
      AND SM_Billing_status__c <> 'PAYMENT COMPLETED'
      AND RecordType.Name IN ('Credit Rectification')
      AND Id NOT IN (
            SELECT SM_Contract__c
            FROM SM_ACH_Order__c
            WHERE SM_Contract__c != null
      )
];

System.debug('\u2192 Contratos detectados SIN ACH Order: ' + contratos.size());
if (contratos.isEmpty()) {
    System.debug('\u2192 ❌ No hay contratos pendientes');
    return;
}

// Listas bulkificadas
List<SM_ACH_Order__c> nuevosOrders = new List<SM_ACH_Order__c>();
List<Contract> contratosACorregir = new List<Contract>();

// 2️⃣ Procesamiento
for (Contract c : contratos) {

    System.debug('↳ Procesando contrato: ' + c.ContractNumber);

    // Validación: Payment Method debe existir
    if (c.SM_Payment_Method__c == null) {
        System.debug('   ❌ Sin Payment Method — omitido');
        continue;
    }

    // Validación: relación Payment Method y su RecordType
    if (c.SM_Payment_Method__r == null || c.SM_Payment_Method__r.RecordType == null) {
        System.debug('   ❌ Payment Method sin RecordType — omitido');
        continue;
    }

    String metodoPM = c.SM_Payment_Method__r.RecordType.Name;

    // Corrección del picklist si está inconsistente
    if (c.SM_Payment_methods__c != metodoPM) {
        System.debug('   ⚠ Inconsistencia detectada \u2192 se corrige a "' + metodoPM + '"');

        contratosACorregir.add(new Contract(
            Id = c.Id,
            SM_Payment_methods__c = metodoPM
        ));

        c.SM_Payment_methods__c = metodoPM; // usar valor corregido en este run
    }

    // Si tras corrección NO es ACH \u2192 omitir
    if (c.SM_Payment_methods__c != 'ACH') {
        System.debug('   ⚠ Contrato NO es ACH — omitido');
        continue;
    }

    // Excluir Chargebee
    if (String.isNotBlank(c.CB_Subscription__c)) {
        System.debug('   ⚠ Contrato Chargebee — omitido');
        continue;
    }

    // ============================================================
    // Crear ACH Order AC o Subscription
    // ============================================================

    if (c.SM_Requires_AC_Payment__c == true) {

        // Validaciones AC
        if (c.SM_Net_AC__c == null) {
            System.debug('   ❌ SM_Net_AC__c vacío — omitido');
            continue;
        }
        if (c.SM_AC_start_date__c == null) {
            System.debug('   ❌ SM_AC_start_date__c vacío — omitido');
            continue;
        }

        nuevosOrders.add(new SM_ACH_Order__c(
            SM_Contract__c              = c.Id,
            SM_Payment_Type__c          = 'AC',
            SM_Payment_Frequency__c     = 'Once',
            SM_Payment_Start_Date__c    = c.SM_AC_start_date__c,
            SM_Payment_End_Date__c      = c.SM_AC_start_date__c,
            SM_Next_Transaction_Date__c = c.SM_AC_start_date__c,
            SM_Payment_Status__c        = 'Pending',
            SM_Payment_Condition__c     = 'Fixed value',
            SM_Billing_Email__c         = c.SM_Email_to_send_contract__c,
            SM_Payment_Count__c         = 1,
            SM_Fee_to_collect__c        = 1,
            SM_Apply_Penalty__c         = false,
            SM_Penalty_Value__c         = 0,
            SM_Payment_Method__c        = c.SM_Payment_Method__c,
            SM_Total__c                 = c.SM_Net_AC__c
        ));

        System.debug('   ↳ ☑ ACH Order AC preparado');
        continue;
    }

    // Subscription
    if (c.SM_Net_Monthly_offer__c == null) {
        System.debug('   ❌ SM_Net_Monthly_offer__c vacío — omitido');
        continue;
    }
    if (c.SM_Start_date__c == null) {
        System.debug('   ❌ SM_Start_date__c vacío — omitido');
        continue;
    }

    nuevosOrders.add(new SM_ACH_Order__c(
        SM_Contract__c              = c.Id,
        SM_Payment_Type__c          = 'Subscription',
        SM_Payment_Frequency__c     = 'Monthly',
        SM_Payment_Start_Date__c    = c.SM_Start_date__c,
        SM_Payment_End_Date__c      = null, // optimizado: suscripción abierta
        SM_Next_Transaction_Date__c = c.SM_Start_date__c,
        SM_Payment_Status__c        = 'Pending',
        SM_Payment_Condition__c     = 'Fixed value',
        SM_Billing_Email__c         = c.SM_Email_to_send_contract__c,
        SM_Payment_Count__c         = 1,
        SM_Fee_to_collect__c        = 1,
        SM_Apply_Penalty__c         = false,
        SM_Penalty_Value__c         = 0,
        SM_Payment_Method__c        = c.SM_Payment_Method__c,
        SM_Total__c                 = c.SM_Net_Monthly_offer__c
    ));

    System.debug('   ↳ ☑ ACH Order Subscription preparado');
}

// Resumen
System.debug('========================================');
System.debug('\u2192 Total ACH Orders a crear: ' + nuevosOrders.size());
System.debug('\u2192 Total Contratos a corregir: ' + contratosACorregir.size());
System.debug('========================================');

// 3️⃣ DML (solo si no es dry run)
if (!modoDryRun) {

    // Correcciones de contratos
    if (!contratosACorregir.isEmpty()) {
        Database.SaveResult[] rc = Database.update(contratosACorregir, false);
        Integer ok = 0;
        for (Integer i = 0; i < rc.size(); i++) {
            if (rc[i].isSuccess()) ok++;
            else System.debug('   ❌ Error corrigiendo ' + contratosACorregir[i].Id + ': ' +
                              rc[i].getErrors()[0].getMessage());
        }
        System.debug('\u2192☑ Contratos corregidos: ' + ok + '/' + contratosACorregir.size());
    }

    // Creación de ACH Orders
    if (!nuevosOrders.isEmpty()) {
        Database.SaveResult[] ro = Database.insert(nuevosOrders, false);
        Integer ok = 0;
        for (Integer i = 0; i < ro.size(); i++) {
            if (ro[i].isSuccess()) ok++;
            else System.debug('   ❌ Error creando ACH Order para ' + nuevosOrders[i].SM_Contract__c + ': ' +
                              ro[i].getErrors()[0].getMessage());
        }
        System.debug('\u2192 ☑ ACH Orders creados: ' + ok + '/' + nuevosOrders.size());
    }

} else {
    System.debug('\u2192 MODO DRY RUN: no se insertó/actualizó nada.');
}