force-app/main/default/objects/Contract/fields/Collection_Main_Contract__c.field-meta.xml
<CustomField>
    <fullName>Collection_Main_Contract__c</fullName>
    <label>Collection Main Contract</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending data capture</fullName>
                <default>true</default>
                <label>Pending data capture</label>
            </value>
            <value>
                <fullName>Ready for collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Unique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Principal_Contract__c.field-meta.xml
<CustomField>
    <fullName>Principal_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Principal Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contracts (Principal Contract)</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_AC_start_date__c.field-meta.xml
<CustomField>
    <fullName>SM_AC_start_date__c</fullName>
    <label>AC start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Company_Setting__c.field-meta.xml
<CustomField>
    <fullName>SM_Company_Setting__c</fullName>
    <formula>CASESAFEID(SM_Opportunity__r.SM_Company_Setting__c)</formula>
    <label>Company Setting</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Frecuency__c.field-meta.xml
<CustomField>
    <fullName>SM_Frecuency__c</fullName>
    <label>Frecuency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Monthly_offer__c.field-meta.xml
<CustomField>
    <fullName>SM_Monthly_offer__c</fullName>
    <label>Net Monthly offer</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SM_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>SM_Payment_Method__c.SM_Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>SM_Payment_Method__c.SM_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SM_Payment_Method__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Plan_Months__c.field-meta.xml
<CustomField>
    <fullName>SM_Plan_Months__c</fullName>
    <label>Plan (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Process_automation_by_product_family__c.field-meta.xml
<CustomField>
    <fullName>SM_Process_automation_by_product_family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process automation by product family</label>
    <referenceTo>Process_automation_by_product_family__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Requires_AC_Payment__c.field-meta.xml
<CustomField>
    <fullName>SM_Requires_AC_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks that based on the product the Ac must be collected</description>
    <inlineHelpText>Marks that based on the product the Ac must be collected</inlineHelpText>
    <label>Requires AC Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Requires_RC_Payment__c.field-meta.xml
<CustomField>
    <fullName>SM_Requires_RC_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires RC Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Start_date__c.field-meta.xml
<CustomField>
    <fullName>SM_Start_date__c</fullName>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Total_ac__c.field-meta.xml
<CustomField>
    <fullName>SM_Total_ac__c</fullName>
    <label>Net AC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Way_of_AC_Payment__c.field-meta.xml
<CustomField>
    <fullName>SM_Way_of_AC_Payment__c</fullName>
    <label>Way of AC Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One payment</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/SM_Way_of_Contract_Payment__c.field-meta.xml
<CustomField>
    <fullName>SM_Way_of_Contract_Payment__c</fullName>
    <label>Way of Contract Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Fix Term</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
                <isActive>false</isActive>
                <label>Fee</label>
            </value>
            <value>
                <fullName>Fees</fullName>
                <isActive>false</isActive>
                <label>Fees</label>
            </value>
            <value>
                <fullName>N/A</fullName>
                <isActive>false</isActive>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/SM_ACH_Order__c.object-meta.xml
<CustomObject>
    <label>ACH Order</label>
    <nameField>
        <displayFormat>ACH-{0000}</displayFormat>
        <label>ACH Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Bank__c.field-meta.xml
<CustomField>
    <fullName>SM_Bank__c</fullName>
    <formula>SM_Payment_Method__r.SM_Bank__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Contract__c.field-meta.xml
<CustomField>
    <fullName>SM_Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>ACH Orders</relationshipLabel>
    <relationshipName>ACH_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Next_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Next_Transaction_Date__c</fullName>
    <label>Next Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Method__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Method</label>
    <referenceTo>SM_Payment_Method__c</referenceTo>
    <relationshipLabel>ACH Orders</relationshipLabel>
    <relationshipName>ACH_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Stopped</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <isActive>false</isActive>
                <label>Complete</label>
            </value>
            <value>
                <fullName>Failed</fullName>
                <isActive>false</isActive>
                <label>Failed</label>
            </value>
            <value>
                <fullName>TBD</fullName>
                <isActive>false</isActive>
                <label>TBD</label>
            </value>
            <value>
                <fullName>X CANCELED</fullName>
                <isActive>false</isActive>
                <label>X CANCELED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Late payment fee</fullName>
            </value>
            <value>
                <fullName>Suscripción</fullName>
                <isActive>false</isActive>
                <label>Suscripción</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_ACH_Order__c/fields/SM_Total__c.field-meta.xml
<CustomField>
    <fullName>SM_Total__c</fullName>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SM_Payment_Method__c/SM_Payment_Method__c.object-meta.xml
<CustomObject>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{000000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SM_Payment_Method__c/fields/SM_Bank__c.field-meta.xml
<CustomField>
    <fullName>SM_Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>SM_Bank__c</referenceTo>
    <relationshipLabel>Payments Methods</relationshipLabel>
    <relationshipName>Payments_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SM_Payment_Method__c/fields/SM_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>SM_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Checking Account</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SM_Payment_Method__c/fields/SM_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>SM_Routing_Number__c</fullName>
    <formula>SM_Bank__r.SM_Routing_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Routing Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SM_ACHPayProcDeployTest.cls
@IsTest
private with sharing class SM_ACHPayProcDeployTest {

    @TestSetup
    static void setupData() {
        insert new SM_Bypasser__c(SM_Disable_Validation_Rules__c = false, SetupOwnerId = UserInfo.getProfileId());

        Account accountRecord = SM_TestSmartDataFactory.getPersonAccount();
        accountRecord.PersonEmail = 'ach.process.deploy@test.invalid';
        insert accountRecord;

        SM_Bank__c bankRecord = new SM_Bank__c(Name = 'Bank ACH Deploy', SM_Routing_Number__c = '987654321');
        insert bankRecord;

        SM_Payment_Method__c achMethod = SM_TestSmartDataFactory.getACHPaymentMethod(accountRecord.Id, 'BANCO POPULAR ACH');
        achMethod.SM_Bank__c = bankRecord.Id;
        insert achMethod;

        SM_Company_setting__c companySetting = SM_TestSmartDataFactory.getCompanySetting();
        insert companySetting;

        Opportunity opportunityRecord = SM_TestSmartDataFactory.getOpportunity();
        opportunityRecord.AccountId = accountRecord.Id;
        opportunityRecord.SM_Company_Setting__c = companySetting.Id;
        insert opportunityRecord;

        Process_automation_by_product_family__c processRecord = SM_TestSmartDataFactory.getProccessAutomation();
        processRecord.Company_setting__c = companySetting.Id;
        insert processRecord;

        insert new SM_Required_Field_Info__c(
            Name = 'ACH Deploy Required',
            SM_Company_Setting__c = companySetting.Id,
            SM_Api_Field_Name__c = 'Id',
            SM_Process__c = 'AC - Full Payment',
            SM_Source_Object__c = 'Contract'
        );

        insert new SM_Required_Field_Info__c(
            Name = 'ACH Subscription Required',
            SM_Company_Setting__c = companySetting.Id,
            SM_Api_Field_Name__c = 'Id',
            SM_Process__c = 'Subscription',
            SM_Source_Object__c = 'Contract'
        );

        Contract masterContract = new Contract(
            AccountId = accountRecord.Id,
            Status = 'Draft',
            StartDate = Date.today(),
            ContractTerm = 12,
            Contract_Type__c = SM_ContractHelper.contractType.MASTER,
            Collection_Main_Contract__c = 'Pending data capture',
            SM_Payment_Method__c = achMethod.Id,
            SM_Opportunity__c = opportunityRecord.Id,
            SM_Requires_AC_Payment__c = true,
            SM_Way_of_AC_Payment__c = 'One payment',
            SM_AC_start_date__c = Date.today().addDays(3),
            SM_Total_AC__c = 100,
            SM_Requires_RC_Payment__c = true,
            SM_Way_of_Contract_Payment__c = 'Subscription',
            SM_Frecuency__c = 'Monthly',
            SM_Start_date__c = Date.today().addDays(5),
            SM_Monthly_offer__c = 80,
            SM_Process_automation_by_product_family__c = processRecord.Id
        );
        insert masterContract;

        List<Contract> dependentContracts = new List<Contract>();
        for (Integer idx = 0; idx < 2; idx++) {
            dependentContracts.add(new Contract(
                AccountId = accountRecord.Id,
                Status = 'Draft',
                StartDate = Date.today(),
                ContractTerm = 12,
                Contract_Type__c = SM_ContractHelper.contractType.DEPENDENT,
                Principal_Contract__c = masterContract.Id,
                Collection_Main_Contract__c = 'Ready for collection',
                SM_Total_ac__c = 50
            ));
        }
        insert dependentContracts;

        insert new SM_ACH_Order__c(
            SM_Contract__c = masterContract.Id,
            SM_Payment_Type__c = SM_ACHOrderHelper.paymentType.SUBSCRIPTION,
            SM_Payment_Status__c = SM_ACHOrderHelper.paymentStatus.PENDING,
            SM_Payment_Method__c = achMethod.Id,
            SM_Total__c = 30,
            SM_Payment_Start_Date__c = Date.today(),
            SM_Next_Transaction_Date__c = Date.today()
        );
    }

    @IsTest
    static void shouldExecuteAchCreationAndSubscriptionPaths() {
        Contract masterContract = [SELECT Id FROM Contract WHERE Contract_Type__c = :SM_ContractHelper.contractType.MASTER LIMIT 1];

        Test.startTest();
            SM_ACHPaymentProcessHandler.CreateACOrderRecordsACH(
                new List<String>{ (String)masterContract.Id },
                new List<Object>{ 'AC - Full Payment' },
                new List<Object>{ SM_ACHOrderHelper.paymentType.AC }
            );
            SM_ACHPaymentProcessHandler.CreateSubscriptionOrderRecordsACH(
                new List<String>{ (String)masterContract.Id }
            );
        Test.stopTest();

        Integer achOrders = [SELECT COUNT() FROM SM_ACH_Order__c WHERE SM_Contract__c = :masterContract.Id];
        System.assert(achOrders >= 1, 'Expected ACH process execution without unhandled exceptions.');
    }

    @IsTest
    static void shouldExecuteAssetFeeBundlePath() {
        List<Contract> dependentContracts = [
            SELECT Id, Contract_Type__c, Principal_Contract__c
            FROM Contract
            WHERE Contract_Type__c = :SM_ContractHelper.contractType.DEPENDENT
            LIMIT 2
        ];

        Test.startTest();
            SM_ACHPaymentProcessHandler.createAssetFeetBoundle(dependentContracts);
        Test.stopTest();

        System.assertEquals(2, dependentContracts.size(), 'Expected dependent contracts prepared for bundle path.');
    }

    @IsTest
    static void shouldCreateFixTermOrders() {
        Account accountRecord = [SELECT Id FROM Account LIMIT 1];
        SM_Payment_Method__c achMethod = [SELECT Id FROM SM_Payment_Method__c LIMIT 1];
        Opportunity opportunityRecord = [SELECT Id FROM Opportunity LIMIT 1];
        Process_automation_by_product_family__c processRecord = [SELECT Id FROM Process_automation_by_product_family__c LIMIT 1];

        Contract splitContract = new Contract(
            AccountId = accountRecord.Id,
            Status = 'Draft',
            StartDate = Date.today(),
            ContractTerm = 12,
            Contract_Type__c = SM_ContractHelper.contractType.MASTER,
            Collection_Main_Contract__c = 'Pending data capture',
            SM_Payment_Method__c = achMethod.Id,
            SM_Opportunity__c = opportunityRecord.Id,
            SM_Requires_AC_Payment__c = true,
            SM_Way_of_AC_Payment__c = 'One payment',
            SM_AC_start_date__c = Date.today().addDays(3),
            SM_Total_AC__c = 120,
            SM_Requires_RC_Payment__c = true,
            SM_Way_of_Contract_Payment__c = 'Fix Term',
            SM_Start_date__c = Date.today().addDays(5),
            SM_Monthly_offer__c = 90,
            SM_Plan_Months__c = 3,
            SM_Process_automation_by_product_family__c = processRecord.Id
        );
        insert splitContract;

        Test.startTest();
            SM_ACHPaymentProcessHandler.CreateACOrderRecordsACH(
                new List<String>{ (String)splitContract.Id },
                new List<Object>{ 'AC - Full Payment' },
                new List<Object>{ SM_ACHOrderHelper.paymentType.AC }
            );
            SM_ACHPaymentProcessHandler.CreateSubscriptionOrderRecordsACH(
                new List<String>{ (String)splitContract.Id }
            );
        Test.stopTest();

        Integer orderCount = [SELECT COUNT() FROM SM_ACH_Order__c WHERE SM_Contract__c = :splitContract.Id];
        System.assert(orderCount >= 2, 'Expected AC plus fix-term orders to be created.');
    }
}